#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Unit tests for kb.py. Run: uv run scripts/tests/test-kb.py"""

import importlib.util
import io
import json
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent.parent / "kb.py"
spec = importlib.util.spec_from_file_location("kb", SCRIPT)
kb = importlib.util.module_from_spec(spec)
spec.loader.exec_module(kb)

GOOD_ENTRY = """---
id: {id}
title: A rule
tag: mechanical
since: 1.40.0
until: '{until}'
supersedes: '{supersedes}'
provenance: framework:Hexalith@v1.40.0
verified: '{verified}'
drained: na
---

# A rule

## Statement

The rule.

## Why

The reason.
"""

META = "---\ntargets_framework: '>= 1.72'\n---\n"

INTAKE = "---\nsource: consult\nfiled: 2026-07-10\nstatus: open\n---\n\n# Question\n"


def make_kb(root: Path, entries: dict, intake: bool = True):
    (root / "entries").mkdir(parents=True)
    (root / "meta.md").write_text(META, encoding="utf-8")
    for name, text in entries.items():
        (root / "entries" / f"{name}.md").write_text(text, encoding="utf-8")
    if intake:
        (root / "intake").mkdir()
        (root / "intake" / "q1.md").write_text(INTAKE, encoding="utf-8")


def run(func, root):
    out = io.StringIO()
    with redirect_stdout(out):
        code = func(root)
    return code, json.loads(out.getvalue())


class KbTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name) / "kb"

    def tearDown(self):
        self.tmp.cleanup()

    def test_frontmatter_parses_flat_fields(self):
        p = Path(self.tmp.name) / "f.md"
        p.write_text("---\nid: x\ntitle: 'Quoted'\n---\nbody", encoding="utf-8")
        fields, body, err = kb.parse_frontmatter(p)
        self.assertIsNone(err)
        self.assertEqual(fields, {"id": "x", "title": "Quoted"})
        self.assertEqual(body, "body")

    def test_frontmatter_rejects_missing_block(self):
        p = Path(self.tmp.name) / "f.md"
        p.write_text("no frontmatter", encoding="utf-8")
        fields, _, err = kb.parse_frontmatter(p)
        self.assertIsNone(fields)
        self.assertIn("frontmatter", err)

    def test_validate_clean_kb_passes(self):
        make_kb(self.root, {"a": GOOD_ENTRY.format(id="a", until="", supersedes="", verified="")})
        code, result = run(kb.cmd_validate, self.root)
        self.assertEqual(code, 0)
        self.assertTrue(result["ok"])
        self.assertEqual(result["checked"], {"entries": 1, "intake": 1})

    def test_validate_flags_schema_violations(self):
        bad = "---\nid: other\ntag: bogus\nsince: 1.0.0\ndrained: maybe\nverified: nope\nsupersedes: ghost\n---\nno sections"
        make_kb(self.root, {"bad": bad}, intake=False)
        code, result = run(kb.cmd_validate, self.root)
        self.assertEqual(code, 1)
        problems = " | ".join(f["problem"] for f in result["findings"])
        for expected in ("'title' missing", "does not match filename", "tag 'bogus'",
                         "drained 'maybe'", "not YYYY-MM-DD", "unknown entry 'ghost'",
                         "'## Statement' missing", "'## Why' missing"):
            self.assertIn(expected, problems)

    def test_validate_missing_root(self):
        code, result = run(kb.cmd_validate, self.root)
        self.assertEqual(code, 1)
        self.assertFalse(result["ok"])

    def test_index_counts_current_and_superseded(self):
        make_kb(self.root, {
            "old": GOOD_ENTRY.format(id="old", until="1.73.0", supersedes="", verified=""),
            "new": GOOD_ENTRY.format(id="new", until="", supersedes="old", verified=""),
        })
        code, result = run(kb.cmd_index, self.root)
        self.assertEqual(code, 0)
        text = (self.root / "index.md").read_text(encoding="utf-8")
        self.assertIn("Generated by kb.py", text)
        self.assertIn("**current:** 1", text)
        self.assertIn("**superseded:** 1", text)
        self.assertIn("| old | A rule | 1.73.0 | new |", text)

    def test_stats_drain_and_verification(self):
        drained = GOOD_ENTRY.format(id="d", until="", supersedes="", verified="2026-07-01").replace("drained: na", "drained: yes")
        pending = GOOD_ENTRY.format(id="p", until="", supersedes="", verified="").replace("drained: na", "drained: no")
        older = GOOD_ENTRY.format(id="o", until="", supersedes="", verified="2026-06-15")
        make_kb(self.root, {"d": drained, "p": pending, "o": older})
        code, result = run(kb.cmd_stats, self.root)
        self.assertEqual(code, 0)
        self.assertEqual(result["drain"]["from_ai_tools"], 2)
        self.assertEqual(result["drain"]["drained"], 1)
        self.assertEqual(result["drain"]["pct"], 50)
        self.assertEqual(result["drain"]["undrained"], [{"id": "p", "provenance": "framework:Hexalith@v1.40.0"}])
        self.assertEqual(result["verification"]["never"], 1)
        self.assertEqual(result["verification"]["never_verified"], ["p"])
        self.assertEqual(result["verification"]["oldest_verified"], "o")
        self.assertEqual(result["intake_open"], 1)
        self.assertEqual(result["targets_framework"], ">= 1.72")

    def test_validate_accepts_absorb_intake_source(self):
        make_kb(self.root, {"a": GOOD_ENTRY.format(id="a", until="", supersedes="", verified="")}, intake=False)
        (self.root / "intake").mkdir()
        (self.root / "intake" / "self.md").write_text(
            "---\nsource: absorb\nfiled: 2026-07-13\nstatus: open\n---\n\n# Gap noticed mid-run\n", encoding="utf-8"
        )
        code, result = run(kb.cmd_validate, self.root)
        self.assertEqual(code, 0)
        self.assertTrue(result["ok"])

    def test_validate_accepts_migrate_extend_and_create_intake_sources(self):
        make_kb(self.root, {"a": GOOD_ENTRY.format(id="a", until="", supersedes="", verified="")}, intake=False)
        (self.root / "intake").mkdir()
        for source in ("migrate", "extend", "create"):
            (self.root / "intake" / f"{source}.md").write_text(
                f"---\nsource: {source}\nfiled: 2026-07-13\nstatus: open\n---\n\n# Gap filed mid-run\n", encoding="utf-8"
            )
        code, result = run(kb.cmd_validate, self.root)
        self.assertEqual(code, 0)
        self.assertTrue(result["ok"])

    def test_validate_rejects_unknown_intake_source(self):
        make_kb(self.root, {"a": GOOD_ENTRY.format(id="a", until="", supersedes="", verified="")}, intake=False)
        (self.root / "intake").mkdir()
        (self.root / "intake" / "bad.md").write_text(
            "---\nsource: wizard\nfiled: 2026-07-13\nstatus: open\n---\n\n# Gap\n", encoding="utf-8"
        )
        code, result = run(kb.cmd_validate, self.root)
        self.assertEqual(code, 1)
        self.assertFalse(result["ok"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
