#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Deterministic operations on the Hexalith conventions knowledge base.

Subcommands:
  validate  Check meta.md, every entry, and every intake file against the KB
            schema. Prints JSON findings; each finding names the file, the
            problem, and the fix. Exit 1 when findings exist.
  index     Regenerate index.md from entries and intake (marked as generated).
  stats     Print compact JSON metrics: entry counts by tag and status, drain
            progress, verification ages, open intake count.

KB layout expected at the root (default: _bmad/hex/knowledge under the current
working directory; override with --kb):
  meta.md            frontmatter: targets_framework
  entries/<id>.md    flat YAML frontmatter: id, title, tag (mechanical|judgment),
                     since, until (empty = current), supersedes (comma-separated
                     ids), provenance, verified (YYYY-MM-DD or empty),
                     drained (yes|no|na); body sections: ## Statement, ## Why
  intake/*.md        frontmatter: source (consult|enforce|migrate|extend|create|human|absorb),
                     filed (YYYY-MM-DD), status (open|resolved)
  index.md           generated by this script
"""

import argparse
import datetime
import json
import re
import sys
from pathlib import Path

REQUIRED_ENTRY_FIELDS = ("id", "title", "tag", "since", "provenance", "drained")
TAGS = {"mechanical", "judgment"}
DRAINED = {"yes", "no", "na"}
INTAKE_SOURCES = {"consult", "enforce", "migrate", "extend", "create", "human", "absorb"}
INTAKE_STATUS = {"open", "resolved"}
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
STALE_DAYS = 90


def parse_frontmatter(path: Path):
    """Parse flat 'key: value' YAML frontmatter. Returns (fields, body, error)."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return None, "", f"unreadable: {exc}"
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None, text, "no frontmatter block (file must start with ---)"
    fields = {}
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return fields, "\n".join(lines[i + 1 :]), None
        if not line.strip():
            continue
        if ":" not in line:
            return None, "", f"frontmatter line {i + 1} is not 'key: value': {line!r}"
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip().strip("'\"")
    return None, "", "frontmatter block never closed with ---"


def load_kb(root: Path):
    kb = {"meta": None, "meta_error": None, "entries": [], "intake": []}
    meta = root / "meta.md"
    if meta.is_file():
        fields, _, err = parse_frontmatter(meta)
        kb["meta"], kb["meta_error"] = fields, err
    entries_dir = root / "entries"
    if entries_dir.is_dir():
        for path in sorted(entries_dir.glob("*.md")):
            fields, body, err = parse_frontmatter(path)
            kb["entries"].append({"path": path, "fm": fields or {}, "body": body, "error": err})
    intake_dir = root / "intake"
    if intake_dir.is_dir():
        for path in sorted(intake_dir.glob("*.md")):
            fields, body, err = parse_frontmatter(path)
            kb["intake"].append({"path": path, "fm": fields or {}, "body": body, "error": err})
    return kb


def rel(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def cmd_validate(root: Path) -> int:
    findings = []

    def add(file, problem, fix):
        findings.append({"file": file, "problem": problem, "fix": fix})

    if not root.is_dir():
        add(str(root), "KB root not found", "run the seed intent to found the KB, or pass --kb <path>")
        print(json.dumps({"ok": False, "findings": findings}, indent=2))
        return 1

    kb = load_kb(root)

    if kb["meta"] is None:
        add("meta.md", kb["meta_error"] or "missing", "create meta.md with frontmatter targets_framework: '>= X.Y'")
    elif not kb["meta"].get("targets_framework"):
        add("meta.md", "targets_framework missing or empty", "add targets_framework: '>= X.Y' to the frontmatter")

    if not (root / "entries").is_dir():
        add("entries/", "entries directory missing", "run the seed intent to found the KB")

    ids = {e["fm"].get("id") for e in kb["entries"] if e["fm"].get("id")}
    for e in kb["entries"]:
        f = rel(e["path"], root)
        if e["error"]:
            add(f, e["error"], "start the file with a flat 'key: value' frontmatter block per assets/entry-template.md")
            continue
        fm = e["fm"]
        for field in REQUIRED_ENTRY_FIELDS:
            if not fm.get(field):
                add(f, f"required field '{field}' missing or empty", f"set '{field}' per assets/entry-template.md")
        if fm.get("id") and fm["id"] != e["path"].stem:
            add(f, f"id '{fm['id']}' does not match filename", f"rename the file to {fm['id']}.md or fix the id")
        if fm.get("tag") and fm["tag"] not in TAGS:
            add(f, f"tag '{fm['tag']}' invalid", "use 'mechanical' or 'judgment'")
        if fm.get("drained") and fm["drained"] not in DRAINED:
            add(f, f"drained '{fm['drained']}' invalid", "use 'yes', 'no', or 'na'")
        if "ai-tools:" in fm.get("provenance", "") and fm.get("drained") == "na":
            add(f, "drained 'na' invalid for ai-tools provenance", "use 'no' until the content is drained from Hexalith.AI.Tools, then 'yes'")
        if fm.get("verified") and not DATE_RE.match(fm["verified"]):
            add(f, f"verified '{fm['verified']}' is not YYYY-MM-DD", "use an ISO date or leave empty")
        for sup in filter(None, (s.strip() for s in fm.get("supersedes", "").split(","))):
            if sup not in ids:
                add(f, f"supersedes references unknown entry '{sup}'", "point at an existing entry id or remove it")
        for section in ("## Statement", "## Why"):
            if section not in e["body"]:
                add(f, f"body section '{section}' missing", "add the section per assets/entry-template.md")

    for it in kb["intake"]:
        f = rel(it["path"], root)
        if it["error"]:
            add(f, it["error"], "start the file with a flat 'key: value' frontmatter block per assets/intake-template.md")
            continue
        fm = it["fm"]
        if fm.get("source") not in INTAKE_SOURCES:
            add(f, f"source '{fm.get('source')}' invalid", "use one of consult, enforce, migrate, extend, create, human, absorb")
        if not DATE_RE.match(fm.get("filed", "")):
            add(f, "filed missing or not YYYY-MM-DD", "set filed to the ISO date the gap was filed")
        if fm.get("status") not in INTAKE_STATUS:
            add(f, f"status '{fm.get('status')}' invalid", "use 'open' or 'resolved'")

    checked = {"entries": len(kb["entries"]), "intake": len(kb["intake"])}
    print(json.dumps({"ok": not findings, "checked": checked, "findings": findings}, indent=2))
    return 1 if findings else 0


def collect(root: Path):
    kb = load_kb(root)
    entries = [e for e in kb["entries"] if not e["error"]]
    current = [e for e in entries if not e["fm"].get("until")]
    superseded = [e for e in entries if e["fm"].get("until")]
    open_intake = [i for i in kb["intake"] if i["fm"].get("status") == "open"]
    return kb, entries, current, superseded, open_intake


def cmd_index(root: Path) -> int:
    kb, entries, current, superseded, open_intake = collect(root)
    superseded_by = {}
    for e in entries:
        for sup in filter(None, (s.strip() for s in e["fm"].get("supersedes", "").split(","))):
            superseded_by.setdefault(sup, []).append(e["fm"].get("id", "?"))
    target = (kb["meta"] or {}).get("targets_framework", "unknown")
    mech = sum(1 for e in current if e["fm"].get("tag") == "mechanical")

    lines = [
        "# Hexalith Conventions KB — Index",
        "",
        "<!-- Generated by kb.py index — do not edit by hand. -->",
        "",
        f"**targets_framework:** `{target}` · **current:** {len(current)} "
        f"({mech} mechanical, {len(current) - mech} judgment) · "
        f"**superseded:** {len(superseded)} · **open intake:** {len(open_intake)}",
        "",
        "## Current conventions",
        "",
        "| id | title | tag | since | verified | drained |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for e in sorted(current, key=lambda e: e["fm"].get("id", "")):
        fm = e["fm"]
        lines.append(
            f"| {fm.get('id', '?')} | {fm.get('title', '?')} | {fm.get('tag', '?')} "
            f"| {fm.get('since', '?')} | {fm.get('verified') or 'never'} | {fm.get('drained', '?')} |"
        )
    if superseded:
        lines += ["", "## Superseded (migration from-states)", "", "| id | title | until | superseded by |", "| --- | --- | --- | --- |"]
        for e in sorted(superseded, key=lambda e: e["fm"].get("id", "")):
            fm = e["fm"]
            by = ", ".join(superseded_by.get(fm.get("id", ""), [])) or "—"
            lines.append(f"| {fm.get('id', '?')} | {fm.get('title', '?')} | {fm.get('until', '?')} | {by} |")
    if open_intake:
        lines += ["", "## Open intake", "", "| file | source | filed |", "| --- | --- | --- |"]
        for i in open_intake:
            lines.append(f"| {rel(i['path'], root)} | {i['fm'].get('source', '?')} | {i['fm'].get('filed', '?')} |")
    lines.append("")

    out = root / "index.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"ok": True, "index": str(out), "entries": len(entries)}))
    return 0


def cmd_stats(root: Path) -> int:
    kb, entries, current, superseded, open_intake = collect(root)
    today = datetime.date.today()
    never = stale = fresh = 0
    never_ids, dated = [], []
    for e in current:
        eid = e["fm"].get("id", "?")
        v = e["fm"].get("verified", "")
        if not DATE_RE.match(v):
            never += 1
            never_ids.append(eid)
        else:
            dated.append((v, eid))
            if (today - datetime.date.fromisoformat(v)).days > STALE_DAYS:
                stale += 1
            else:
                fresh += 1
    from_ai_tools = [e for e in entries if e["fm"].get("drained") in ("yes", "no")]
    drained = sum(1 for e in from_ai_tools if e["fm"].get("drained") == "yes")
    undrained = [
        {"id": e["fm"].get("id", "?"), "provenance": e["fm"].get("provenance", "")}
        for e in from_ai_tools
        if e["fm"].get("drained") == "no"
    ]
    print(
        json.dumps(
            {
                "ok": True,
                "targets_framework": (kb["meta"] or {}).get("targets_framework"),
                "entries": {
                    "current": len(current),
                    "superseded": len(superseded),
                    "mechanical": sum(1 for e in current if e["fm"].get("tag") == "mechanical"),
                    "judgment": sum(1 for e in current if e["fm"].get("tag") == "judgment"),
                    "unparseable": sum(1 for e in kb["entries"] if e["error"]),
                },
                "drain": {
                    "from_ai_tools": len(from_ai_tools),
                    "drained": drained,
                    "pct": round(100 * drained / len(from_ai_tools)) if from_ai_tools else 100,
                    "undrained": undrained,
                },
                "verification": {
                    "never": never,
                    f"stale_{STALE_DAYS}d": stale,
                    "fresh": fresh,
                    "never_verified": sorted(never_ids),
                    "oldest_verified": min(dated)[1] if dated else None,
                },
                "intake_open": len(open_intake),
            },
            indent=2,
        )
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["validate", "index", "stats"])
    parser.add_argument("--kb", default="_bmad/hex/knowledge", help="KB root (default: _bmad/hex/knowledge under the cwd)")
    args = parser.parse_args()
    root = Path(args.kb)
    return {"validate": cmd_validate, "index": cmd_index, "stats": cmd_stats}[args.command](root)


if __name__ == "__main__":
    sys.exit(main())
